name: npm_install
description: Install npm packages
runs:
  using: composite
  steps:
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: Install dependencies
      run: npm install
      shell: bash
