name: Javascript Workflow
on:
  push:
    branches:
      - new_branch
jobs:
  javascript_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: './.github/actions/javascript'
