name: 'Test workflow'
on:
  push:
    branches:
      - bbbranch
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
        with:
          node-version: 18.x
      - name: Install dependencies
        uses: './.github/actions/install_deps_from_cache'
      - name: 'Run tests'
        run: npm run test
