name: "Test workflow"
on: 
  push:
    branches:
      - bbbranch
  pull_request:
    types: [opened, synchronize, edited]   

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
            node-version: 20.x
      - name: Install dependencies
        uses: "./.github/actions/install_deps_from_cache"
      - name: "Run tests"
        run: npm run test